// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	entity "crud/entity"

	mock "github.com/stretchr/testify/mock"
)

// CustomerInterfaceRepo is an autogenerated mock type for the CustomerInterfaceRepo type
type CustomerInterfaceRepo struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: customer
func (_m *CustomerInterfaceRepo) CreateCustomer(customer *entity.Customer) (*entity.Customer, error) {
	ret := _m.Called(customer)

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Customer) (*entity.Customer, error)); ok {
		return rf(customer)
	}
	if rf, ok := ret.Get(0).(func(*entity.Customer) *entity.Customer); ok {
		r0 = rf(customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Customer) error); ok {
		r1 = rf(customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCustomerById provides a mock function with given fields: id
func (_m *CustomerInterfaceRepo) DeleteCustomerById(id uint) (entity.Customer, error) {
	ret := _m.Called(id)

	var r0 entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entity.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) entity.Customer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerById provides a mock function with given fields: id
func (_m *CustomerInterfaceRepo) GetCustomerById(id uint) (entity.Customer, error) {
	ret := _m.Called(id)

	var r0 entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entity.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) entity.Customer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomers provides a mock function with given fields: name, email, page
func (_m *CustomerInterfaceRepo) GetCustomers(name string, email string, page uint) ([]entity.Customer, error) {
	ret := _m.Called(name, email, page)

	var r0 []entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, uint) ([]entity.Customer, error)); ok {
		return rf(name, email, page)
	}
	if rf, ok := ret.Get(0).(func(string, string, uint) []entity.Customer); ok {
		r0 = rf(name, email, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, uint) error); ok {
		r1 = rf(name, email, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomerById provides a mock function with given fields: customer, id
func (_m *CustomerInterfaceRepo) UpdateCustomerById(customer *entity.Customer, id uint) (*entity.Customer, error) {
	ret := _m.Called(customer, id)

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Customer, uint) (*entity.Customer, error)); ok {
		return rf(customer, id)
	}
	if rf, ok := ret.Get(0).(func(*entity.Customer, uint) *entity.Customer); ok {
		r0 = rf(customer, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Customer, uint) error); ok {
		r1 = rf(customer, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCustomerInterfaceRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerInterfaceRepo creates a new instance of CustomerInterfaceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerInterfaceRepo(t mockConstructorTestingTNewCustomerInterfaceRepo) *CustomerInterfaceRepo {
	mock := &CustomerInterfaceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
