version: '3'
services:
  app:
    image: crm-service-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crm_service
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
